changed event systems to have a local states

diff --git a/Scripts/run_game b/Scripts/run_game
--- a/Scripts/run_game
+++ b/Scripts/run_game
@@ -2,9 +2,13 @@
 project_root=$(dirname $(dirname "$0"))
 cd $project_root
 
-echo "> Building game ..."
-cmake --build build --config Release --target Game
-echo "> Game built."
+build_game
+build_game_result=$?
 
-cd built_data
-Game
+if [ $build_game_result != 0 ]; then
+    echo "> Build failed; won't execute game"
+    exit $build_game_result
+else
+    cd built_data
+    Game
+fi
